server:
  port: 9000
spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
    nacos:
      username: nacos
      password: nacos
      server-addr: http://localhost:8848
      discovery:
        enabled: true
        namespace: public
        group: DEFAULT_GROUP
  application:
    name: gateway
