server:
  port: 9010
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: http://localhost:8848
      discovery:
        enabled: true
        namespace: public
        group: DEFAULT_GROUP
  application:
    name: user-service
